# Imports

In [75]:
import os
import sys
from pathlib import Path

import pandas as pd

sys.path.append(os.path.abspath("..\src"))

from config import CITIES, START_DATE, END_DATE, DAILY_VARIABLES
from ingestion import fetch_all_cities, fetch_forecast_all_cities

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
C:\Users\royan\AppData\Local\Temp\ipykernel_22568\1057069948.py:7: SyntaxWarning: invalid escape sequence '\s'
  sys.path.append(os.path.abspath("..\src"))

# Create output folders

In [77]:
raw_historical_dir = Path("../data/raw/historical")
raw_forecast_dir = Path("../data/raw/forecast")

raw_historical_dir.mkdir(parents=True, exist_ok=True)
raw_forecast_dir.mkdir(parents=True, exist_ok=True)

print("Historical folder:", raw_historical_dir.resolve())
print("Forecast folder:", raw_forecast_dir.resolve())

Historical folder: C:\Users\royan\Desktop\m5-project-weather-pipeline\data\raw\historical
Forecast folder: C:\Users\royan\Desktop\m5-project-weather-pipeline\data\raw\forecast

# Quick config check

In [80]:
print("Cities:")
for city in CITIES:
    print(city)

print("\nDate range:")
print(START_DATE, "→", END_DATE)

print("\nDaily variables:")
print(DAILY_VARIABLES)

Cities:
{'name': 'Baku', 'latitude': 40.41, 'longitude': 49.87}
{'name': 'Lankaran', 'latitude': 38.75, 'longitude': 48.85}
{'name': 'Guba', 'latitude': 41.36, 'longitude': 48.51}
{'name': 'Gabala', 'latitude': 40.58, 'longitude': 47.5}
{'name': 'Shaki', 'latitude': 41.11, 'longitude': 47.1}

Date range:
2020-01-01 → 2025-12-31

Daily variables:
['temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration']

# Fetch historical data for all cities

In [83]:
historical_data = fetch_all_cities(
    cities_config=CITIES,
    start_date=START_DATE,
    end_date=END_DATE,
    variables=DAILY_VARIABLES,
)

Fetching historical data for Baku...
Baku: 2192 historical rows
Fetching historical data for Lankaran...
Lankaran: 2192 historical rows
Fetching historical data for Guba...
Guba: 2192 historical rows
Fetching historical data for Gabala...
Gabala: 2192 historical rows
Fetching historical data for Shaki...
Shaki: 2192 historical rows

# Inspect historical data

In [85]:
for city_name, df in historical_data.items():
    print(f"\nCity: {city_name}")
    print(f"Rows: {len(df)}")
    print(f"Columns: {list(df.columns)}")
    print(f"Date range: {df['time'].min()} → {df['time'].max()}")
    print("Missing values:")
    print(df.isna().sum())

City: Baku
Rows: 2192
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2020-01-01 00:00:00 → 2025-12-31 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Lankaran
Rows: 2192
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2020-01-01 00:00:00 → 2025-12-31 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Guba
Rows: 2192
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2020-01-01 00:00:00 → 2025-12-31 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Gabala
Rows: 2192
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2020-01-01 00:00:00 → 2025-12-31 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Shaki
Rows: 2192
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2020-01-01 00:00:00 → 2025-12-31 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

# Save historical raw files

In [87]:
for city_name, df in historical_data.items():
    file_path = raw_historical_dir / f"{city_name.lower()}_2020_2025.parquet"
    df.to_parquet(file_path, index=False)
    print(f"Saved historical file: {file_path}")

Saved historical file: ..\data\raw\historical\baku_2020_2025.parquet
Saved historical file: ..\data\raw\historical\lankaran_2020_2025.parquet
Saved historical file: ..\data\raw\historical\guba_2020_2025.parquet
Saved historical file: ..\data\raw\historical\gabala_2020_2025.parquet
Saved historical file: ..\data\raw\historical\shaki_2020_2025.parquet

# Verify saved historical files

In [89]:
for file in sorted(raw_historical_dir.glob("*.parquet")):
    print(f"\nFile: {file.name}")
    df_check = pd.read_parquet(file)
    print(df_check.head(3))
    print(df_check.shape)

File: baku_2020_2025.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2020-01-01                11.4                0.0                11.4
1 2020-01-02                 8.6                0.0                33.0
2 2020-01-03                 7.6                1.7                24.1

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         90                30                       8.8
1                         88                50                       3.2
2                         83                96                       3.3

   sunshine_duration  city
0           31885.13  Baku
1           30162.88  Baku
2            1147.69  Baku
(2192, 9)

File: gabala_2020_2025.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2020-01-01                11.4                0.0                11.0
1 2020-01-02                 9.4                0.5                11.5
2 2020-01-03                 6.1                2.8                 8.9

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         86                38                       8.3
1                         83                56                       7.4
2                         95                95                       3.9

   sunshine_duration    city
0           27993.24  Gabala
1           21233.07  Gabala
2               0.00  Gabala
(2192, 9)

File: guba_2020_2025.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2020-01-01                 8.0                0.0                10.1
1 2020-01-02                 2.2                1.6                10.7
2 2020-01-03                 0.6                3.2                 7.4

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         69                 5                       4.5
1                         90                76                      -0.7
2                         87               100                      -2.8

   sunshine_duration  city
0           31374.47  Guba
1               0.00  Guba
2               0.00  Guba
(2192, 9)

File: lankaran_2020_2025.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2020-01-01                11.9                0.9                 7.6
1 2020-01-02                11.5                4.2                17.8
2 2020-01-03                 8.4               16.2                17.8

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         85                35                      10.3
1                         76                46                       9.7
2                         91               100                       5.5

   sunshine_duration      city
0           29333.76  Lankaran
1           30200.26  Lankaran
2               0.00  Lankaran
(2192, 9)

File: shaki_2020_2025.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2020-01-01                 9.4                0.0                10.5
1 2020-01-02                 8.5                0.6                11.8
2 2020-01-03                 4.9                4.2                11.8

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         80                13                       6.2
1                         77                35                       5.9
2                         93                95                       1.4

   sunshine_duration   city
0           30452.33  Shaki
1           30789.31  Shaki
2           12711.48  Shaki
(2192, 9)

# Fetch forecast data for all cities

In [91]:
forecast_data = fetch_forecast_all_cities(
    cities_config=CITIES,
    variables=DAILY_VARIABLES,
)

Fetching forecast data for Baku...
Baku: 7 forecast rows
Fetching forecast data for Lankaran...
Lankaran: 7 forecast rows
Fetching forecast data for Guba...
Guba: 7 forecast rows
Fetching forecast data for Gabala...
Gabala: 7 forecast rows
Fetching forecast data for Shaki...
Shaki: 7 forecast rows

# Inspect forecast data

In [93]:
for city_name, df in forecast_data.items():
    print(f"\nCity: {city_name}")
    print(f"Rows: {len(df)}")
    print(f"Columns: {list(df.columns)}")
    print(f"Date range: {df['time'].min()} → {df['time'].max()}")
    print("Missing values:")
    print(df.isna().sum())

City: Baku
Rows: 7
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2026-04-25 00:00:00 → 2026-05-01 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Lankaran
Rows: 7
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2026-04-25 00:00:00 → 2026-05-01 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Guba
Rows: 7
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2026-04-25 00:00:00 → 2026-05-01 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Gabala
Rows: 7
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2026-04-25 00:00:00 → 2026-05-01 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

City: Shaki
Rows: 7
Columns: ['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']
Date range: 2026-04-25 00:00:00 → 2026-05-01 00:00:00
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

# Save forecast raw files

In [99]:
for city_name, df in forecast_data.items():
    file_path = raw_forecast_dir / f"{city_name.lower()}_forecast.parquet"
    df.to_parquet(file_path, index=False)
    print(f"Saved forecast file: {file_path}")

Saved forecast file: ..\data\raw\forecast\baku_forecast.parquet
Saved forecast file: ..\data\raw\forecast\lankaran_forecast.parquet
Saved forecast file: ..\data\raw\forecast\guba_forecast.parquet
Saved forecast file: ..\data\raw\forecast\gabala_forecast.parquet
Saved forecast file: ..\data\raw\forecast\shaki_forecast.parquet

# Verify saved forecast files

In [101]:
for file in sorted(raw_forecast_dir.glob("*.parquet")):
    print(f"\nFile: {file.name}")
    df_check = pd.read_parquet(file)
    print(df_check.head(3))
    print(df_check.shape)

File: baku_forecast.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2026-04-25                14.8                0.0                30.2
1 2026-04-26                16.0                0.0                25.5
2 2026-04-27                18.8                0.2                50.8

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         80                78                      13.7
1                         81                44                      13.6
2                         78                83                      18.0

   sunshine_duration  city
0           29133.25  Baku
1           46698.68  Baku
2           26936.03  Baku
(7, 9)

File: gabala_forecast.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2026-04-25                20.9                0.0                34.4
1 2026-04-26                18.9                0.0                15.7
2 2026-04-27                23.6                0.4                22.1

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         49                23                      15.1
1                         72                34                      18.8
2                         69                92                      21.4

   sunshine_duration    city
0           44578.85  Gabala
1           44856.28  Gabala
2           24414.30  Gabala
(7, 9)

File: guba_forecast.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2026-04-25                 9.2                2.1                16.7
1 2026-04-26                13.6                0.0                 9.4
2 2026-04-27                17.0                4.2                17.6

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         90                98                       7.0
1                         88                66                      12.6
2                         81                90                      17.3

   sunshine_duration  city
0            7534.98  Guba
1           43653.54  Guba
2            8209.79  Guba
(7, 9)

File: lankaran_forecast.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2026-04-25                21.6                0.1                23.7
1 2026-04-26                16.5                0.0                16.6
2 2026-04-27                19.0                3.6                28.2

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         60                72                      18.7
1                         83                94                      15.7
2                         87                98                      20.5

   sunshine_duration      city
0           40923.27  Lankaran
1           24207.27  Lankaran
2           16508.02  Lankaran
(7, 9)

File: shaki_forecast.parquet
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2026-04-25                18.6                0.1                44.2
1 2026-04-26                17.8                0.0                16.8
2 2026-04-27                20.9                0.0                25.9

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         52                29                      11.4
1                         75                54                      16.8
2                         73                93                      20.7

   sunshine_duration   city
0           42861.38  Shaki
1           44271.80  Shaki
2           27364.81  Shaki
(7, 9)

# Combine historical data into one dataframe

In [103]:
historical_all = pd.concat(historical_data.values(), ignore_index=True)
historical_all = historical_all.sort_values(["city", "time"]).reset_index(drop=True)

print(historical_all.shape)
print(historical_all.head())

(10960, 9)
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2020-01-01                11.4                0.0                11.4
1 2020-01-02                 8.6                0.0                33.0
2 2020-01-03                 7.6                1.7                24.1
3 2020-01-04                 8.4                0.2                22.7
4 2020-01-05                 7.7                2.6                12.6

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         90                30                       8.8
1                         88                50                       3.2
2                         83                96                       3.3
3                         83                98                       4.6
4                         91               100                       6.4

   sunshine_duration  city
0           31885.13  Baku
1           30162.88  Baku
2            1147.69  Baku
3            1300.71  Baku
4               0.00  Baku

# Combine forecast data into one dataframe

In [105]:
forecast_all = pd.concat(forecast_data.values(), ignore_index=True)
forecast_all = forecast_all.sort_values(["city", "time"]).reset_index(drop=True)

print(forecast_all.shape)
print(forecast_all.head())

(35, 9)
        time  temperature_2m_max  precipitation_sum  wind_speed_10m_max  \
0 2026-04-25                14.8                0.0                30.2
1 2026-04-26                16.0                0.0                25.5
2 2026-04-27                18.8                0.2                50.8
3 2026-04-28                14.5                0.0                44.1
4 2026-04-29                15.7                0.3                12.6

   relative_humidity_2m_mean  cloud_cover_mean  apparent_temperature_max  \
0                         80                78                      13.7
1                         81                44                      13.6
2                         78                83                      18.0
3                         54                85                       8.7
4                         71                96                      14.4

   sunshine_duration  city
0           29133.25  Baku
1           46698.68  Baku
2           26936.03  Baku
3           30387.62  Baku
4           13624.88  Baku

# Final raw-data sanity checks

In [107]:
print("Historical duplicate rows:", historical_all.duplicated().sum())
print("Forecast duplicate rows:", forecast_all.duplicated().sum())

print("\nHistorical date range:", historical_all["time"].min(), "→", historical_all["time"].max())
print("Forecast date range:", forecast_all["time"].min(), "→", forecast_all["time"].max())

print("\nHistorical columns:")
print(historical_all.columns.tolist())

print("\nForecast columns:")
print(forecast_all.columns.tolist())

Historical duplicate rows: 0
Forecast duplicate rows: 0

Historical date range: 2020-01-01 00:00:00 → 2025-12-31 00:00:00
Forecast date range: 2026-04-25 00:00:00 → 2026-05-01 00:00:00

Historical columns:
['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']

Forecast columns:
['time', 'temperature_2m_max', 'precipitation_sum', 'wind_speed_10m_max', 'relative_humidity_2m_mean', 'cloud_cover_mean', 'apparent_temperature_max', 'sunshine_duration', 'city']

# DuckDB Loading

In [70]:
%pip install duckdb

Collecting duckdb
  Downloading duckdb-1.5.2-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.2-cp312-cp312-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/13.1 MB 2.6 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/13.1 MB 3.4 MB/s eta 0:00:04
   ------- -------------------------------- 2.4/13.1 MB 3.5 MB/s eta 0:00:04
   --------- ------------------------------ 3.1/13.1 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/13.1 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 4.5/13.1 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/13.1 MB 3.4 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/13.1 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 7.1/13.1 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.9/13.1 MB 3.8 MB/s eta 0:00:02
   -------------------------- ------------- 8.7/13.1 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 9.2/13.1 MB 3.7 MB/s eta 0:00:02
   ------------------------------ --------- 10.0/13.1 MB 3.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.7/13.1 MB 3.7 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/13.1 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 12.3/13.1 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  12.8/13.1 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 3.6 MB/s eta 0:00:00
Installing collected packages: duckdb
Successfully installed duckdb-1.5.2
Note: you may need to restart the kernel to use updated packages.

In [119]:
from src.db import create_schemas, load_raw_data, run_query

create_schemas()
load_raw_data()

run_query("SELECT * FROM raw.historical LIMIT 5")

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2020-01-01,11.4,0.0,11.4,90,30,8.8,31885.13,Baku
1,2020-01-02,8.6,0.0,33.0,88,50,3.2,30162.88,Baku
2,2020-01-03,7.6,1.7,24.1,83,96,3.3,1147.69,Baku
3,2020-01-04,8.4,0.2,22.7,83,98,4.6,1300.71,Baku
4,2020-01-05,7.7,2.6,12.6,91,100,6.4,0.00,Baku

In [125]:
run_query("""
SELECT table_schema, table_name
FROM information_schema.tables
""")

  table_schema  table_name
0          raw    forecast
1          raw  historical