In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [3]:
import pandas as pd

from src.db import run_query

from src.quality_checks import (
    check_missing_values,
    check_duplicate_rows,
    check_duplicate_city_dates,
    check_date_coverage,
    check_missing_dates,
    check_column_consistency,
    check_weather_ranges,
)

In [5]:
historical_df = run_query("SELECT * FROM raw.historical")
forecast_df = run_query("SELECT * FROM raw.forecast")

historical_df.head()

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2020-01-01,11.4,0.0,11.4,90,30,8.8,31885.13,Baku
1,2020-01-02,8.6,0.0,33.0,88,50,3.2,30162.88,Baku
2,2020-01-03,7.6,1.7,24.1,83,96,3.3,1147.69,Baku
3,2020-01-04,8.4,0.2,22.7,83,98,4.6,1300.71,Baku
4,2020-01-05,7.7,2.6,12.6,91,100,6.4,0.00,Baku

In [11]:
forecast_df.head()

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2026-04-25,14.8,0.0,30.2,80,78,13.7,29133.25,Baku
1,2026-04-26,16.0,0.0,25.5,81,44,13.6,46698.68,Baku
2,2026-04-27,18.8,0.2,50.8,78,83,18.0,26936.03,Baku
3,2026-04-28,14.5,0.0,44.1,54,85,8.7,30387.62,Baku
4,2026-04-29,15.7,0.3,12.6,71,96,14.4,13624.88,Baku

In [21]:
print("HISTORICAL DATA CHECKS")

print("Missing values:")
print(check_missing_values(historical_df))

print("\nDuplicate rows:")
print(check_duplicate_rows(historical_df))

print("\nDuplicate city-date:")
print(check_duplicate_city_dates(historical_df))

print("\nWeather ranges:")
print(check_weather_ranges(historical_df))

HISTORICAL DATA CHECKS
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

Duplicate rows:
0

Duplicate city-date:
0

Weather ranges:
{'temperature_2m_max': 0, 'precipitation_sum': 0, 'wind_speed_10m_max': 0, 'relative_humidity_2m_mean': 0, 'cloud_cover_mean': 0, 'apparent_temperature_max': 0, 'sunshine_duration': 0}

In [23]:
print("=== FORECAST DATA CHECKS ===")

print("\nMissing values:")
print(check_missing_values(forecast_df))

print("\nDuplicate rows:")
print(check_duplicate_rows(forecast_df))

print("\nDuplicate city-date:")
print(check_duplicate_city_dates(forecast_df))

print("\nWeather ranges:")
print(check_weather_ranges(forecast_df))

=== FORECAST DATA CHECKS ===

Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

Duplicate rows:
0

Duplicate city-date:
0

Weather ranges:
{'temperature_2m_max': 0, 'precipitation_sum': 0, 'wind_speed_10m_max': 0, 'relative_humidity_2m_mean': 0, 'cloud_cover_mean': 0, 'apparent_temperature_max': 0, 'sunshine_duration': 0}

In [19]:
check_column_consistency(historical_df, forecast_df)

{'same_columns': True, 'only_in_first': [], 'only_in_second': []}

In [26]:
print("City coverage:")
print(historical_df["city"].value_counts())

print("\nForecast city coverage:")
print(forecast_df["city"].value_counts())

City coverage:
city
Baku        2192
Gabala      2192
Guba        2192
Lankaran    2192
Shaki       2192
Name: count, dtype: int64

Forecast city coverage:
city
Baku        7
Gabala      7
Guba        7
Lankaran    7
Shaki       7
Name: count, dtype: int64

In [28]:
print("Date coverage:")
print(check_date_coverage(historical_df))

print("\nMissing dates:")
print(check_missing_dates(historical_df))

Date coverage:
                min        max  count
city
Baku     2020-01-01 2025-12-31   2192
Gabala   2020-01-01 2025-12-31   2192
Guba     2020-01-01 2025-12-31   2192
Lankaran 2020-01-01 2025-12-31   2192
Shaki    2020-01-01 2025-12-31   2192

Missing dates:
{'Baku': 0, 'Gabala': 0, 'Guba': 0, 'Lankaran': 0, 'Shaki': 0}

### Data Quality Summary

Both historical and forecast datasets were checked for missing values, duplicate rows, duplicate city-date records, date coverage, city coverage, and unrealistic weather values.
The checks show that the datasets are complete, consistent, and suitable for the next pipeline steps: cleaning, feature engineering, and model preparation.

## Data Cleaning Test

In [49]:
import importlib
import src.cleaning
importlib.reload(src.cleaning)

from src.cleaning import clean_data
from src.db import run_query

In [51]:
raw_df = run_query("SELECT * FROM raw.historical")
clean_df = clean_data(raw_df)
clean_df.head()

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2020-01-01,11.4,0.0,11.4,90,30,8.8,31885.13,Baku
1,2020-01-02,8.6,0.0,33.0,88,50,3.2,30162.88,Baku
2,2020-01-03,7.6,1.7,24.1,83,96,3.3,1147.69,Baku
3,2020-01-04,8.4,0.2,22.7,83,98,4.6,1300.71,Baku
4,2020-01-05,7.7,2.6,12.6,91,100,6.4,0.00,Baku

In [53]:
print("After cleaning:")

print("\nMissing values:")
print(clean_df.isna().sum())

print("\nDuplicates:")
print(clean_df.duplicated().sum())

After cleaning:

Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

Duplicates:
0

In [55]:
print(clean_df.shape)
print(raw_df.shape)

(10960, 9)
(10960, 9)

In [58]:
clean_df.groupby("city")["time"].diff().value_counts()

time
1 days    10955
Name: count, dtype: int64

### Data Cleaning Summary

The dataset was cleaned by converting date columns, fixing data types, removing duplicates, and handling missing values. 

After cleaning:
- No missing values remain
- No duplicate records exist
- Data structure is consistent across all cities
- Time series continuity is preserved

The dataset is now ready for feature engineering.