In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [2]:
import pandas as pd

from src.db import run_query

from src.quality_checks import (
    check_missing_values,
    check_duplicate_rows,
    check_duplicate_city_dates,
    check_date_coverage,
    check_missing_dates,
    check_column_consistency,
    check_weather_ranges,
)

In [3]:
historical_df = run_query("SELECT * FROM raw.historical")
forecast_df = run_query("SELECT * FROM raw.forecast")

historical_df.head()

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2020-04-27,19.3,0.0,15.9,78,26,19.8,45068.90,Baku
1,2020-04-28,14.6,0.0,42.0,83,71,11.9,38436.84,Baku
2,2020-04-29,17.6,0.0,22.4,61,50,16.3,39311.92,Baku
3,2020-04-30,18.0,0.0,23.0,77,50,16.0,44363.33,Baku
4,2020-05-01,19.5,0.0,20.2,78,24,18.5,46341.87,Baku

In [4]:
forecast_df.head()

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2026-04-28,14.1,0.0,45.5,51,91,7.1,32312.05,Baku
1,2026-04-29,11.4,2.0,26.2,68,100,6.6,0.00,Baku
2,2026-04-30,17.8,0.0,19.7,62,45,19.1,45458.65,Baku
3,2026-05-01,17.6,0.0,35.1,81,33,14.0,48264.58,Baku
4,2026-05-02,19.4,0.0,27.0,80,42,17.2,46696.39,Baku

In [5]:
print("HISTORICAL DATA CHECKS")

print("Missing values:")
print(check_missing_values(historical_df))

print("\nDuplicate rows:")
print(check_duplicate_rows(historical_df))

print("\nDuplicate city-date:")
print(check_duplicate_city_dates(historical_df))

print("\nWeather ranges:")
print(check_weather_ranges(historical_df))

HISTORICAL DATA CHECKS
Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

Duplicate rows:
0

Duplicate city-date:
0

Weather ranges:
{'temperature_2m_max': 0, 'precipitation_sum': 0, 'wind_speed_10m_max': 0, 'relative_humidity_2m_mean': 0, 'cloud_cover_mean': 0, 'apparent_temperature_max': 0, 'sunshine_duration': 0}

In [6]:
print("=== FORECAST DATA CHECKS ===")

print("\nMissing values:")
print(check_missing_values(forecast_df))

print("\nDuplicate rows:")
print(check_duplicate_rows(forecast_df))

print("\nDuplicate city-date:")
print(check_duplicate_city_dates(forecast_df))

print("\nWeather ranges:")
print(check_weather_ranges(forecast_df))

=== FORECAST DATA CHECKS ===

Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

Duplicate rows:
0

Duplicate city-date:
0

Weather ranges:
{'temperature_2m_max': 0, 'precipitation_sum': 0, 'wind_speed_10m_max': 0, 'relative_humidity_2m_mean': 0, 'cloud_cover_mean': 0, 'apparent_temperature_max': 0, 'sunshine_duration': 0}

In [7]:
check_column_consistency(historical_df, forecast_df)

{'same_columns': True, 'only_in_first': [], 'only_in_second': []}

In [8]:
print("City coverage:")
print(historical_df["city"].value_counts())

print("\nForecast city coverage:")
print(forecast_df["city"].value_counts())

City coverage:
city
Baku        2192
Gabala      2192
Guba        2192
Lankaran    2192
Shaki       2192
Name: count, dtype: int64

Forecast city coverage:
city
Baku        7
Gabala      7
Guba        7
Lankaran    7
Shaki       7
Name: count, dtype: int64

In [9]:
print("Date coverage:")
print(check_date_coverage(historical_df))

print("\nMissing dates:")
print(check_missing_dates(historical_df))

Date coverage:
                min        max  count
city
Baku     2020-04-27 2026-04-27   2192
Gabala   2020-04-27 2026-04-27   2192
Guba     2020-04-27 2026-04-27   2192
Lankaran 2020-04-27 2026-04-27   2192
Shaki    2020-04-27 2026-04-27   2192

Missing dates:
{'Baku': 0, 'Gabala': 0, 'Guba': 0, 'Lankaran': 0, 'Shaki': 0}

### Data Quality Summary

Both historical and forecast datasets were checked for missing values, duplicate rows, duplicate city-date records, date coverage, city coverage, and unrealistic weather values.
The checks show that the datasets are complete, consistent, and suitable for the next pipeline steps: cleaning, feature engineering, and model preparation.

## Data Cleaning Test

In [10]:
import importlib
import src.cleaning
importlib.reload(src.cleaning)

from src.cleaning import clean_data
from src.db import run_query

In [11]:
raw_df = run_query("SELECT * FROM raw.historical")
clean_df = clean_data(raw_df)
clean_df.head()

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city
0,2020-04-27,19.3,0.0,15.9,78,26,19.8,45068.90,Baku
1,2020-04-28,14.6,0.0,42.0,83,71,11.9,38436.84,Baku
2,2020-04-29,17.6,0.0,22.4,61,50,16.3,39311.92,Baku
3,2020-04-30,18.0,0.0,23.0,77,50,16.0,44363.33,Baku
4,2020-05-01,19.5,0.0,20.2,78,24,18.5,46341.87,Baku

In [12]:
print("After cleaning:")

print("\nMissing values:")
print(clean_df.isna().sum())

print("\nDuplicates:")
print(clean_df.duplicated().sum())

After cleaning:

Missing values:
time                         0
temperature_2m_max           0
precipitation_sum            0
wind_speed_10m_max           0
relative_humidity_2m_mean    0
cloud_cover_mean             0
apparent_temperature_max     0
sunshine_duration            0
city                         0
dtype: int64

Duplicates:
0

In [13]:
print(clean_df.shape)
print(raw_df.shape)

(10960, 9)
(10960, 9)

In [14]:
clean_df.groupby("city")["time"].diff().value_counts()

time
1 days    10955
Name: count, dtype: int64

### Data Cleaning Summary

The dataset was cleaned by converting date columns, fixing data types, removing duplicates, and handling missing values. 

After cleaning:
- No missing values remain
- No duplicate records exist
- Data structure is consistent across all cities
- Time series continuity is preserved

The dataset is now ready for feature engineering.

## Feature Engineering (Test)

In [15]:
from src.features import build_features
feature_df, le = build_features(clean_df)
print(feature_df.shape)
feature_df.head()

(10955, 20)

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city,month,day_of_month,temperature_lag_1,precipitation_lag_1,wind_lag_1,humidity_lag_1,temperature_3d_avg,precipitation_7d_sum,wind_3d_avg,humidity_7d_avg,city_encoded
0,2020-04-28,14.6,0.0,42.0,83,71,11.9,38436.84,Baku,4,28,19.3,0.0,15.9,78.0,16.950000,0.0,28.950000,80.500000,0
1,2020-04-29,17.6,0.0,22.4,61,50,16.3,39311.92,Baku,4,29,14.6,0.0,42.0,83.0,17.166667,0.0,26.766667,74.000000,0
2,2020-04-30,18.0,0.0,23.0,77,50,16.0,44363.33,Baku,4,30,17.6,0.0,22.4,61.0,16.733333,0.0,29.133333,74.750000,0
3,2020-05-01,19.5,0.0,20.2,78,24,18.5,46341.87,Baku,5,1,18.0,0.0,23.0,77.0,18.366667,0.0,21.866667,75.400000,0
4,2020-05-02,19.6,0.0,20.7,83,45,19.0,43993.52,Baku,5,2,19.5,0.0,20.2,78.0,19.033333,0.0,21.300000,76.666667,0

## Store Model-Ready Dataset in DuckDB

In [16]:
from src.db import get_connection

conn = get_connection()

conn.register("feature_df_view", feature_df)

conn.execute("""
CREATE SCHEMA IF NOT EXISTS analytics;
""")

conn.execute("""
CREATE OR REPLACE TABLE analytics.model_features AS
SELECT * FROM feature_df_view;
""")

conn.close()

In [17]:
run_query("SELECT COUNT(*) FROM analytics.model_features")

   count_star()
0         10955

In [18]:
run_query("SELECT * FROM analytics.model_features LIMIT 5")

,time,temperature_2m_max,precipitation_sum,wind_speed_10m_max,relative_humidity_2m_mean,cloud_cover_mean,apparent_temperature_max,sunshine_duration,city,month,day_of_month,temperature_lag_1,precipitation_lag_1,wind_lag_1,humidity_lag_1,temperature_3d_avg,precipitation_7d_sum,wind_3d_avg,humidity_7d_avg,city_encoded
0,2020-04-28,14.6,0.0,42.0,83,71,11.9,38436.84,Baku,4,28,19.3,0.0,15.9,78.0,16.950000,0.0,28.950000,80.500000,0
1,2020-04-29,17.6,0.0,22.4,61,50,16.3,39311.92,Baku,4,29,14.6,0.0,42.0,83.0,17.166667,0.0,26.766667,74.000000,0
2,2020-04-30,18.0,0.0,23.0,77,50,16.0,44363.33,Baku,4,30,17.6,0.0,22.4,61.0,16.733333,0.0,29.133333,74.750000,0
3,2020-05-01,19.5,0.0,20.2,78,24,18.5,46341.87,Baku,5,1,18.0,0.0,23.0,77.0,18.366667,0.0,21.866667,75.400000,0
4,2020-05-02,19.6,0.0,20.7,83,45,19.0,43993.52,Baku,5,2,19.5,0.0,20.2,78.0,19.033333,0.0,21.300000,76.666667,0

In [19]:
run_query("SHOW TABLES FROM analytics")

                  name
0  future_28d_forecast
1       model_features